apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-dev-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/EdgarHarutyunyan2025/argocd
    targetRevision: main 
    path: "helm-chart/dev/" 
    helm:
      releaseName: dev
      valueFiles:
        - dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

