apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-prod-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/EdgarHarutyunyan2025/argocd
    targetRevision: HEAD 
    path: "../helm-chart/" 
    helm:
      releaseName: prod
      valueFiles:
        - prod/prod-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

